### ISSUE TITLE
Please make a Gihub Release and CmakeLists.txt

### ISSUE THREAD

**Issue by Longwater1234** [Nats-ji/i18n-cpp-header-only-library#2]
- Thanks for making this lib. Can you make a Github Release so it is easier to PULL & integrate quickly in other project using `Cmake FetchContent` using URL (of the `tar.gz` release), instead of unstable GIT Cloning. Thanks

**Comment by Nats-ji** [comment]
This project is no longer active. i recommend you use tinygettext instead. it has more complete features https://github.com/tinygettext/tinygettext
